import { IStruct } from "./interfaces";

// https://www.w3.org/TR/WGSL/#type-defining-keywords
export const structs: IStruct[] = [
    { name: 'array', snippet: '<${1|bool,i32,u32,f32,f16|},$2>$0' },
    { name: 'atomic', snippet: '<${1|u32,i32|}>' },
    { name: 'bool' },
    { name: 'f32', description: 'float32' },
    { name: 'f16', description: 'float16' },
    { name: 'i32', description: 'int32' },
    { name: 'mat2x2', snippet: '<${1|f32,f16|}>$0' },
    { name: 'mat2x3', snippet: '<${1|f32,f16|}>$0' },
    { name: 'mat2x4', snippet: '<${1|f32,f16|}>$0' },
    { name: 'mat3x2', snippet: '<${1|f32,f16|}>$0' },
    { name: 'mat3x3', snippet: '<${1|f32,f16|}>$0' },
    { name: 'mat3x4', snippet: '<${1|f32,f16|}>$0' },
    { name: 'mat4x2', snippet: '<${1|f32,f16|}>$0' },
    { name: 'mat4x3', snippet: '<${1|f32,f16|}>$0' },
    { name: 'mat4x4', snippet: '<${1|f32,f16|}>$0' },
    { name: 'ptr', description: 'pointer' },
    { name: 'sampler', description: 'pointer' },
    { name: 'sampler_comparison' },
    { name: 'texture_1d' },
    { name: 'texture_2d' },
    { name: 'texture_2d_array' },
    { name: 'texture_3d' },
    { name: 'texture_cube' },
    { name: 'texture_cube_array' },
    { name: 'texture_multisampled_2d' },
    { name: 'texture_storage_1d' },
    { name: 'texture_storage_2d' },
    { name: 'texture_storage_2d_array' },
    { name: 'texture_storage_3d' },
    { name: 'texture_depth_2d' },
    { name: 'texture_depth_2d_array' },
    { name: 'texture_depth_cube' },
    { name: 'texture_depth_cube_array' },
    { name: 'texture_depth_multisampled_2d' },
    { name: 'u32' },
    { name: 'vec2', snippet: '<${1|bool,i32,u32,f32,f16|}>$0' },
    { name: 'vec3', snippet: '<${1|bool,i32,u32,f32,f16|}>$0' },
    { name: 'vec4', snippet: '<${1|bool,i32,u32,f32,f16|}>$0' },
];